<div id="imageModal" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModal()">&times;</span>

        {{-- Image Counter --}}
        <div id="imageCounter" class="image-counter">1 / 1</div>

        {{-- Navigation Buttons --}}
        <button id="modalPrev" class="modal-nav modal-prev" onclick="previousImage(); event.stopPropagation();">
            ‹
        </button>

        <button id="modalNext" class="modal-nav modal-next" onclick="nextImage(); event.stopPropagation();">
            ›
        </button>

        {{-- Main Image --}}
        <img id="modalImage" src="" alt="Detail Image">

        {{-- Thumbnail Preview --}}
        <div class="thumbnail-container">
            <div class="thumbnail-wrapper" id="thumbnailWrapper">
                {{-- Thumbnails will be generated by JavaScript --}}
            </div>
        </div>

        {{-- Keyboard Hint --}}
        <div class="keyboard-hint">
            Gunakan ← → untuk navigasi atau ESC untuk tutup
        </div>
    </div>
</div>
